apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop-helm-chart.fullname" . }}-nodemanager
  labels:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: nodemanager
spec:
  type: ClusterIP
  ports:
    - port: 8042
      targetPort: 8042
      protocol: TCP
      name: http
  selector:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: nodemanager