apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hadoop-helm-chart.fullname" . }}-resourcemanager
  labels:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: resourcemanager
spec:
  replicas: {{ .Values.yarn.resourcemanager.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop-helm-chart.name" . }}
      component: resourcemanager
  template:
    metadata:
      labels:
        app: {{ include "hadoop-helm-chart.name" . }}
        component: resourcemanager
    spec:
      containers:
        - name: resourcemanager
          image: {{ .Values.yarn.resourcemanager.image.repository }}:{{ .Values.yarn.resourcemanager.image.tag }}
          ports:
            - containerPort: 8088
          env:
            - name: HADOOP_CONF_DIR
              value: /etc/hadoop/conf
          volumeMounts:
            - name: hadoop-config
              mountPath: /etc/hadoop/conf
      volumes:
        - name: hadoop-config
          configMap:
            name: {{ include "hadoop-helm-chart.fullname" . }}-configmap