apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop-helm-chart.fullname" . }}-resourcemanager
  labels:
    app: {{ include "hadoop-helm-chart.name" . }}
    chart: {{ include "hadoop-helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: {{ include "hadoop-helm-chart.fullname" . }}-resourcemanager