apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop-helm-chart.fullname" . }}-datanode
  labels:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: datanode
spec:
  type: ClusterIP
  ports:
    - port: 50010
      targetPort: 50010
      protocol: TCP
      name: datanode
  selector:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: datanode