apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop-helm-chart.fullname" . }}-namenode
  labels:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: namenode
spec:
  type: ClusterIP
  ports:
    - port: 9870
      targetPort: 9870
      protocol: TCP
      name: http
    - port: 8020
      targetPort: 8020
      protocol: TCP
      name: rpc
  selector:
    app: {{ include "hadoop-helm-chart.name" . }}
    component: namenode