apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
    component: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
      component: namenode
  template:
    metadata:
      labels:
        app: hdfs
        component: namenode
    spec:
      containers:
        - name: namenode
          image: <your-namenode-image>
          ports:
            - containerPort: 9870
          env:
            - name: HDFS_NAMENODE_NAME_DIR
              value: /hadoop/dfs/name
          volumeMounts:
            - name: namenode-storage
              mountPath: /hadoop/dfs/name
      volumes:
        - name: namenode-storage
          persistentVolumeClaim:
            claimName: namenode-pvc