apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName | default "hadoop-config" }}
data:
  hdfs-site.xml: |
    <configuration>
    {{- range $key, $value := .Values.hdfs.config }}
      <property>
        <name>{{ $key }}</name>
        <value>{{ $value }}</value>
      </property>
    {{- end }}
    </configuration>
  core-site.xml: |
    <configuration>
    {{- range $key, $value := .Values.core.config }}
      <property>
        <name>{{ $key }}</name>
        <value>{{ $value }}</value>
      </property>
    {{- end }}
    </configuration>
  yarn-site.xml: |
    <configuration>
    {{- range $key, $value := .Values.yarn.config }}
      <property>
        <name>{{ $key }}</name>
        <value>{{ $value }}</value>
      </property>
    {{- end }}
    </configuration>